[package]
name = "rust-web"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.7"
sea-orm = "0.12"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.10", features = ["v7"] }
