version: 2
updates:
- package-ecosystem: cargo
  directory: /fusion
  schedule:
    interval: weekly
    day: monday
- package-ecosystem: cargo
  directory: /pola
  schedule:
    interval: weekly
    day: monday
