version: 2
updates:
- package-ecosystem: pip
  directory: /ml2022
  schedule:
    interval: weekly
    day: friday
- package-ecosystem: cargo
  directory: /try-ballista
  schedule:
    interval: weekly
    day: friday
- package-ecosystem: cargo
  directory: /try-datafusion
  schedule:
    interval: weekly
    day: friday
