version: 2
updates:
  - package-ecosystem: cargo
    directory: "/panopticon"
    schedule:
      interval: weekly
      day: friday
  - package-ecosystem: gomod
    directory: "/go118"
    schedule:
      interval: weekly
      day: friday
