version: 2
updates:
- package-ecosystem: cargo
  directory: /train
  schedule:
    interval: weekly
    day: sunday
- package-ecosystem: cargo
  directory: /fusion
  schedule:
    interval: weekly
    day: sunday
