version: 2
updates:
  - package-ecosystem: cargo
    directory: "/panopticon"
    schedule:
      interval: weekly
      day: friday
- package-ecosystem: gomod
  directory: /go119
  schedule:
    interval: weekly
    day: friday
