version: 2
updates:
- package-ecosystem: cargo
  directory: /ballista-demos
  schedule:
    interval: weekly
    day: monday
- package-ecosystem: cargo
  directory: /datafusion-demos
  schedule:
    interval: weekly
    day: monday
