version: 2
updates:
- package-ecosystem: pip
  directory: /ml2022
  schedule:
    interval: weekly
    day: friday
- package-ecosystem: cargo
  directory: /try-s2n-quic
  schedule:
    interval: weekly
    day: friday
- package-ecosystem: cargo
  directory: /wasm-proxy-filter
  schedule:
    interval: weekly
    day: friday
