[tool.poetry]
name = "rpy"
version = "0.1.0"
description = ""
authors = ["haoxin <haoxinst@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
pylance = "0.3"
black = "23"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
