[tool.poetry]
name = "polapy"
version = "0.1.0"
description = "demo"
authors = ["haoxin <haoxinst@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
polars = "^0.16.11"
requests = "^2.28.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
