[package]
name = "FHE"
edition = "2021"
publish = false

[dependencies]
concrete-fft = "0.4"
dyn-stack = "0.9"
num-complex = "0.4"
tfhe = { version = "0.7", features = [
  "boolean",
  "shortint",
  "integer",
  "x86_64-unix"
] }
