
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - job.flink.io
  resources:
  - versionedjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - job.flink.io
  resources:
  - versionedjobs/finalizers
  verbs:
  - update
- apiGroups:
  - job.flink.io
  resources:
  - versionedjobs/status
  verbs:
  - get
  - patch
  - update
