# permissions for end users to edit versionedjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: versionedjob-editor-role
rules:
- apiGroups:
  - job.flink.io
  resources:
  - versionedjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - job.flink.io
  resources:
  - versionedjobs/status
  verbs:
  - get
